import type { DetailTab, PropertyField } from '../types'

export const PROPERTY_DETAIL_TABS = [
  'Overview', 'Finance', 'Letting Agent', 'Managing Agent',
  'Body Corp', 'Municipal', 'Insurance', 'Tenants', 'Documents',
] as const

// Section key matches DetailTab name (excluding 'Documents')
export const PROPERTY_SECTIONS: Record<DetailTab, PropertyField[]> = {
  'Overview': [
    { key: 'address', label: 'Full Street Address' },
    { key: 'suburb', label: 'Suburb' },
    { key: 'township', label: 'Township' },
    { key: 'unit_number', label: 'Unit Number' },
    { key: 'door_number', label: 'Door Number' },
    { key: 'erf_number', label: 'ERF Number' },
    { key: 'scheme_name', label: 'Scheme Name' },
    { key: 'scheme_number', label: 'Scheme Number' },
    { key: 'size_sqm', label: 'Size (m²)', type: 'number' },
    { key: 'bedrooms', label: 'Bedrooms', type: 'number' },
    { key: 'bathrooms', label: 'Bathrooms', type: 'number' },
    { key: 'parking_bays', label: 'Parking Bays', type: 'number' },
    { key: 'lpi_code', label: 'LPI Code' },
    { key: 'purchase_date', label: 'Purchase Date' },
    { key: 'purchase_price', label: 'Purchase Price', type: 'number', format: 'currency' },
    { key: 'current_market_value', label: 'Current Market Value', type: 'number', format: 'currency' },
    { key: 'valuation_date', label: 'Valuation Date' },
    { key: 'title_deed_reference', label: 'Title Deed Reference' },
    { key: 'owner_name', label: 'Owner Name' },
    { key: 'owner_id', label: 'Owner ID / Reg No.' },
    { key: 'registered_owner', label: 'Registered Owner' },
  ],
  'Finance': [
    { key: 'bond_bank', label: 'Bond Bank' },
    { key: 'bond_account_number', label: 'Bond Account Number' },
    { key: 'original_bond_amount', label: 'Original Bond Amount', type: 'number', format: 'currency' },
    { key: 'bond_endorsement', label: 'Bond Endorsement', type: 'number', format: 'currency' },
    { key: 'bond_endorsement_date', label: 'Endorsement Date' },
    { key: 'monthly_bond_payment', label: 'Monthly Bond Payment', type: 'number', format: 'currency' },
    { key: 'expected_payoff_date', label: 'Expected Payoff Date' },
    { key: 'bond_status', label: 'Bond Status' },
    { key: 'branch', label: 'Rental Bank Branch' },
    { key: 'branch_code', label: 'Rental Bank Branch Code' },
  ],
  'Letting Agent': [
    { key: 'agency', label: 'Letting Agency' },
    { key: 'portfolio_manager', label: 'Portfolio Manager' },
    { key: 'agent_email', label: 'Agent Email' },
    { key: 'agent_phone', label: 'Agent Phone' },
    { key: 'account_administrator', label: 'Account Administrator' },
    { key: 'maintenance_manager', label: 'Maintenance Manager' },
    { key: 'department_head', label: 'Department Head' },
    { key: 'management_fee', label: 'Management Fee' },
    { key: 'payment_method', label: 'Payment Method' },
  ],
  'Managing Agent': [
    { key: 'managing_agency', label: 'Managing Agency' },
    { key: 'managing_agent_name', label: 'Managing Agent' },
    { key: 'portfolio_manager', label: 'Portfolio Manager' },
    { key: 'agent_email', label: 'Agent Email' },
    { key: 'agent_phone', label: 'Agent Phone' },
  ],
  'Body Corp': [
    { key: 'bc_name', label: 'BC Name' },
    { key: 'bc_registration_number', label: 'BC Registration Number' },
    { key: 'bc_contact_name', label: 'BC Contact Name' },
    { key: 'bc_contact_phone', label: 'BC Contact Phone' },
    { key: 'bc_contact_email', label: 'BC Contact Email' },
    { key: 'bc_bank', label: 'BC Bank' },
    { key: 'bc_account_name', label: 'BC Account Name' },
    { key: 'bc_branch', label: 'BC Branch' },
    { key: 'bc_branch_code', label: 'BC Branch Code' },
    { key: 'bc_account_number', label: 'BC Account Number' },
    { key: 'bc_levy_reference', label: 'BC Levy Reference' },
    { key: 'bc_levy_payment_method', label: 'BC Levy Payment Method' },
  ],
  'Municipal': [
    { key: 'municipality_name', label: 'Municipality' },
    { key: 'municipal_account_number', label: 'Municipal Account Number' },
    { key: 'municipal_valuation', label: 'Municipal Valuation', type: 'number', format: 'currency' },
    { key: 'municipal_valuation_year', label: 'Municipal Valuation Year' },
    { key: 'municipal_paid_by', label: 'Paid By' },
  ],
  'Insurance': [
    { key: 'insurer', label: 'Insurer' },
    { key: 'broker', label: 'Broker' },
    { key: 'policy_number', label: 'Policy Number' },
    { key: 'policy_holder', label: 'Policy Holder' },
    { key: 'geyser_excess', label: 'Geyser Excess', type: 'number', format: 'currency' },
    { key: 'annual_renewal_date', label: 'Annual Renewal Date' },
    { key: 'insurance_contact', label: 'Insurance Contact' },
  ],
  'Tenants': [
    { key: 'tenant_name', label: 'Tenant Name' },
    { key: 'tenant_phone', label: 'Tenant Phone' },
    { key: 'tenant_email', label: 'Tenant Email' },
    { key: 'tenant_notes', label: 'Tenant Notes' },
    { key: 'lease_expiry', label: 'Lease Expiry' },
    { key: 'emergency_contact_name', label: 'Emergency Contact' },
    { key: 'emergency_contact_phone', label: 'Emergency Phone' },
    { key: 'emergency_contact_email', label: 'Emergency Email' },
    { key: 'emergency_contact_notes', label: 'Emergency Notes' },
  ],
}

// Order of sectioned fields in the edit form
export const EDIT_SECTION_ORDER: readonly DetailTab[] = [
  'Overview', 'Finance', 'Letting Agent', 'Managing Agent',
  'Body Corp', 'Municipal', 'Insurance', 'Tenants',
] as const
